<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DuW Havelland GmbH</title>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Roboto', sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f5f5f5;
    }
    header {
      background: #2c3e50;
      color: white;
      padding: 20px;
      text-align: center;
      position: sticky;
      top: 0;
      z-index: 100;
    }
    nav ul {
      list-style-type: none;
      padding: 0;
      display: flex;
      justify-content: center;
    }
    nav ul li {
      margin: 0 15px;
    }
    nav ul li a {
      color: white;
      text-decoration: none;
      font-weight: bold;
    }
    .hero {
      background-image: url('hero-image.jpg');
      height: 400px;
      background-size: cover;
      background-position: center;
      position: relative;
      display: flex;
      justify-content: center;
      align-items: center;
      color: white;
      text-align: center;
    }
    .hero h1 {
      font-size: 48px;
      margin: 0;
    }
    .content {
      padding: 40px;
      text-align: center;
    }
    .content h2 {
      margin-bottom: 20px;
    }
    .card-container {
      display: flex;
      justify-content: space-around;
      flex-wrap: wrap;
    }
    .card {
      background-color: white;
      width: 300px;
      margin: 10px;
      padding: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      transition: transform 0.2s;
    }
    .card:hover {
      transform: scale(1.05);
    }
    footer {
      background: #2c3e50;
      color: white;
      text-align: center;
      padding: 20px;
    }
    button {
      background-color: #3498db;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
    }
    button:hover {
      background-color: #2980b9;
    }
  </style>
</head>
<body>
  <header>
    <h1>DuW Havelland GmbH</h1>
    <nav>
      <ul>
        <li><a href="#about">About Us</a></li>
        <li><a href="#services">Services</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </nav>
  </header>

  <section class="hero">
    <h1>Welcome to DuW Havelland</h1>
    <button>Get a Quote</button>
  </section>

  <section class="content" id="about">
    <h2>About Us</h2>
    <p>We provide top-notch environmental and consulting services...</p>
  </section>

  <section class="content" id="services">
    <h2>Our Services</h2>
    <div class="card-container">
      <div class="card">
        <h3>Service 1</h3>
        <p>Description of service 1.</p>
      </div>
      <div class="card">
        <h3>Service 2</h3>
        <p>Description of service 2.</p>
      </div>
      <div class="card">
        <h3>Service 3</h3>
        <p>Description of service 3.</p>
      </div>
    </div>
  </section>

  <footer>
    <p>&copy; 2024 DuW Havelland GmbH. All Rights Reserved.</p>
  </footer>

  <script>
    document.querySelector('button').addEventListener('click', function() {
      window.location.href = "#contact";
    });
  </script>
</body>
</html>

